//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.24 at 11:55:59 AM EDT 
//


package com.apria.gateway.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Address complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Address"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Address_Business_Name" minOccurs="0"/&gt;
 *         &lt;element ref="{}Address_Line_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}Address_Line_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}City" minOccurs="0"/&gt;
 *         &lt;element ref="{}State" minOccurs="0"/&gt;
 *         &lt;element ref="{}Zip" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Address", propOrder = {
    "addressBusinessName",
    "addressLine1",
    "addressLine2",
    "city",
    "state",
    "zip"
})
public class Address {

    @XmlElement(name = "Address_Business_Name")
    protected AddressBusinessName addressBusinessName;
    @XmlElement(name = "Address_Line_1")
    protected AddressLine1 addressLine1;
    @XmlElement(name = "Address_Line_2")
    protected AddressLine2 addressLine2;
    @XmlElement(name = "City")
    protected City city;
    @XmlElement(name = "State")
    protected State state;
    @XmlElement(name = "Zip")
    protected Zip zip;

    /**
     * Gets the value of the addressBusinessName property.
     * 
     * @return
     *     possible object is
     *     {@link AddressBusinessName }
     *     
     */
    public AddressBusinessName getAddressBusinessName() {
        return addressBusinessName;
    }

    /**
     * Sets the value of the addressBusinessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressBusinessName }
     *     
     */
    public void setAddressBusinessName(AddressBusinessName value) {
        this.addressBusinessName = value;
    }

    /**
     * Gets the value of the addressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link AddressLine1 }
     *     
     */
    public AddressLine1 getAddressLine1() {
        return addressLine1;
    }

    /**
     * Sets the value of the addressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressLine1 }
     *     
     */
    public void setAddressLine1(AddressLine1 value) {
        this.addressLine1 = value;
    }

    /**
     * Gets the value of the addressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link AddressLine2 }
     *     
     */
    public AddressLine2 getAddressLine2() {
        return addressLine2;
    }

    /**
     * Sets the value of the addressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressLine2 }
     *     
     */
    public void setAddressLine2(AddressLine2 value) {
        this.addressLine2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link City }
     *     
     */
    public City getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link City }
     *     
     */
    public void setCity(City value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link State }
     *     
     */
    public State getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link State }
     *     
     */
    public void setState(State value) {
        this.state = value;
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link Zip }
     *     
     */
    public Zip getZip() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zip }
     *     
     */
    public void setZip(Zip value) {
        this.zip = value;
    }

}
