//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.24 at 11:55:59 AM EDT 
//


package com.apria.gateway.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Coverages complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Coverages"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Coverage_Line" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element name="Visiting_Member" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element name="Payor_Group" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element name="MBI" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Coverages", propOrder = {
    "coverageLine",
    "visitingMember",
    "payorGroup",
    "mbi"
})
public class Coverages {

    @XmlElement(name = "Coverage_Line")
    protected Object coverageLine;
    @XmlElement(name = "Visiting_Member")
    protected Object visitingMember;
    @XmlElement(name = "Payor_Group")
    protected Object payorGroup;
    @XmlElement(name = "MBI")
    protected Object mbi;

    /**
     * Gets the value of the coverageLine property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCoverageLine() {
        return coverageLine;
    }

    /**
     * Sets the value of the coverageLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCoverageLine(Object value) {
        this.coverageLine = value;
    }

    /**
     * Gets the value of the visitingMember property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVisitingMember() {
        return visitingMember;
    }

    /**
     * Sets the value of the visitingMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVisitingMember(Object value) {
        this.visitingMember = value;
    }

    /**
     * Gets the value of the payorGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPayorGroup() {
        return payorGroup;
    }

    /**
     * Sets the value of the payorGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPayorGroup(Object value) {
        this.payorGroup = value;
    }

    /**
     * Gets the value of the mbi property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMBI() {
        return mbi;
    }

    /**
     * Sets the value of the mbi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMBI(Object value) {
        this.mbi = value;
    }

}
