//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.24 at 11:55:59 AM EDT 
//


package com.apria.gateway.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KP_Order complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KP_Order"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Order_Header"/&gt;
 *         &lt;element ref="{}Order_Equipment" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Delivery_Addresses" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Order_Notes" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KP_Order", propOrder = {
    "orderHeader",
    "orderEquipment",
    "deliveryAddresses",
    "orderNotes"
})
public class KPOrder {

    @XmlElement(name = "Order_Header", required = true)
    protected OrderHeader orderHeader;
    @XmlElement(name = "Order_Equipment")
    protected List<OrderEquipment> orderEquipment;
    @XmlElement(name = "Delivery_Addresses")
    protected List<DeliveryAddresses> deliveryAddresses;
    @XmlElement(name = "Order_Notes")
    protected List<OrderNotes> orderNotes;

    /**
     * Gets the value of the orderHeader property.
     * 
     * @return
     *     possible object is
     *     {@link OrderHeader }
     *     
     */
    public OrderHeader getOrderHeader() {
        return orderHeader;
    }

    /**
     * Sets the value of the orderHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderHeader }
     *     
     */
    public void setOrderHeader(OrderHeader value) {
        this.orderHeader = value;
    }

    /**
     * Gets the value of the orderEquipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderEquipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderEquipment }
     * 
     * 
     */
    public List<OrderEquipment> getOrderEquipment() {
        if (orderEquipment == null) {
            orderEquipment = new ArrayList<OrderEquipment>();
        }
        return this.orderEquipment;
    }

    /**
     * Gets the value of the deliveryAddresses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deliveryAddresses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeliveryAddresses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeliveryAddresses }
     * 
     * 
     */
    public List<DeliveryAddresses> getDeliveryAddresses() {
        if (deliveryAddresses == null) {
            deliveryAddresses = new ArrayList<DeliveryAddresses>();
        }
        return this.deliveryAddresses;
    }

    /**
     * Gets the value of the orderNotes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderNotes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderNotes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderNotes }
     * 
     * 
     */
    public List<OrderNotes> getOrderNotes() {
        if (orderNotes == null) {
            orderNotes = new ArrayList<OrderNotes>();
        }
        return this.orderNotes;
    }

}
