//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.24 at 11:55:59 AM EDT 
//


package com.apria.gateway.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Line_Note complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Line_Note"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Line_Note_ID"/&gt;
 *         &lt;element ref="{}Line_Note_Text"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Line_Note", propOrder = {
    "lineNoteID",
    "lineNoteText"
})
public class LineNote {

    @XmlElement(name = "Line_Note_ID", required = true)
    protected LineNoteID lineNoteID;
    @XmlElement(name = "Line_Note_Text", required = true)
    protected LineNoteText lineNoteText;

    /**
     * Gets the value of the lineNoteID property.
     * 
     * @return
     *     possible object is
     *     {@link LineNoteID }
     *     
     */
    public LineNoteID getLineNoteID() {
        return lineNoteID;
    }

    /**
     * Sets the value of the lineNoteID property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineNoteID }
     *     
     */
    public void setLineNoteID(LineNoteID value) {
        this.lineNoteID = value;
    }

    /**
     * Gets the value of the lineNoteText property.
     * 
     * @return
     *     possible object is
     *     {@link LineNoteText }
     *     
     */
    public LineNoteText getLineNoteText() {
        return lineNoteText;
    }

    /**
     * Sets the value of the lineNoteText property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineNoteText }
     *     
     */
    public void setLineNoteText(LineNoteText value) {
        this.lineNoteText = value;
    }

}
