//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.24 at 11:55:59 AM EDT 
//


package com.apria.gateway.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.apria.gateway.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _KPOrder_QNAME = new QName("", "KP_Order");
    private final static QName _OrderHeader_QNAME = new QName("", "Order_Header");
    private final static QName _Order_QNAME = new QName("", "Order");
    private final static QName _VendorID_QNAME = new QName("", "Vendor_ID");
    private final static QName _KPOrderID_QNAME = new QName("", "KP_Order_ID");
    private final static QName _VendorOrderID_QNAME = new QName("", "Vendor_Order_ID");
    private final static QName _OrderLocation_QNAME = new QName("", "Order_Location");
    private final static QName _TransactionType_QNAME = new QName("", "Transaction_Type");
    private final static QName _OrderID_QNAME = new QName("", "Order_ID");
    private final static QName _OrderType_QNAME = new QName("", "Order_Type");
    private final static QName _PayorGroup_QNAME = new QName("", "Payor_Group");
    private final static QName _MBI_QNAME = new QName("", "MBI");
    private final static QName _ICDCD_QNAME = new QName("", "ICD_CD");
    private final static QName _ICDIND_QNAME = new QName("", "ICD_IND");
    private final static QName _PlaceOfService_QNAME = new QName("", "Place_Of_Service");
    private final static QName _NotificationSentDate_QNAME = new QName("", "Notification_Sent_Date");
    private final static QName _NotificationSentTime_QNAME = new QName("", "Notification_Sent_Time");
    private final static QName _OrderEquipment_QNAME = new QName("", "Order_Equipment");
    private final static QName _DeliveryAddresses_QNAME = new QName("", "Delivery_Addresses");
    private final static QName _OrderNotes_QNAME = new QName("", "Order_Notes");
    private final static QName _TransactionDetails_QNAME = new QName("", "Transaction_Details");
    private final static QName _OrderEquipmentLine_QNAME = new QName("", "Order_Equipment_Line");
    private final static QName _OrderLine_QNAME = new QName("", "Order_Line");
    private final static QName _LineAddressType_QNAME = new QName("", "Line_Address_Type");
    private final static QName _LineCoverage_QNAME = new QName("", "Line_Coverage");
    private final static QName _LineItemCode_QNAME = new QName("", "Line_Item_Code");
    private final static QName _LineItemDescription_QNAME = new QName("", "Line_Item_Description");
    private final static QName _LineItemQuantity_QNAME = new QName("", "Line_Item_Quantity");
    private final static QName _LineServiceStartDate_QNAME = new QName("", "Line_Service_Start_Date");
    private final static QName _LineDurationUnit_QNAME = new QName("", "Line_Duration_Unit");
    private final static QName _LineDurationOfUse_QNAME = new QName("", "Line_Duration_Of_Use");
    private final static QName _LineDeliveryType_QNAME = new QName("", "Line_Delivery_Type");
    private final static QName _ErrorCodes_QNAME = new QName("", "Error_Codes");
    private final static QName _LineNotes_QNAME = new QName("", "Line_Notes");
    private final static QName _LineNote_QNAME = new QName("", "Line_Note");
    private final static QName _LineNoteID_QNAME = new QName("", "Line_Note_ID");
    private final static QName _LineNoteText_QNAME = new QName("", "Line_Note_Text");
    private final static QName _LineCoPayMethod_QNAME = new QName("", "Line_CoPay_Method");
    private final static QName _LineCoPayAmount_QNAME = new QName("", "Line_CoPay_Amount");
    private final static QName _LineMemberLiability_QNAME = new QName("", "Line_Member_Liability");
    private final static QName _LineKPShare_QNAME = new QName("", "Line_KP_Share");
    private final static QName _LineMedicareShare_QNAME = new QName("", "Line_Medicare_Share");
    private final static QName _LineRetrievalDate_QNAME = new QName("", "Line_Retrieval_Date");
    private final static QName _LineRetrievalReason_QNAME = new QName("", "Line_Retrieval_Reason");
    private final static QName _LineRetrievalType_QNAME = new QName("", "Line_Retrieval_Type");
    private final static QName _DeliveryAddress_QNAME = new QName("", "Delivery_Address");
    private final static QName _AddressType_QNAME = new QName("", "Address_Type");
    private final static QName _PrimaryPhone_QNAME = new QName("", "Primary_Phone");
    private final static QName _SecondaryPhone_QNAME = new QName("", "Secondary_Phone");
    private final static QName _OrderNote_QNAME = new QName("", "Order_Note");
    private final static QName _OrderNoteID_QNAME = new QName("", "Order_Note_ID");
    private final static QName _OrderNoteText_QNAME = new QName("", "Order_Note_Text");
    private final static QName _ContactPerson_QNAME = new QName("", "Contact_Person");
    private final static QName _Phone_QNAME = new QName("", "Phone");
    private final static QName _Physician_QNAME = new QName("", "Physician");
    private final static QName _UPIN_QNAME = new QName("", "UPIN");
    private final static QName _NPIID_QNAME = new QName("", "NPI_ID");
    private final static QName _Patient_QNAME = new QName("", "Patient");
    private final static QName _MRN_QNAME = new QName("", "MRN");
    private final static QName _DOB_QNAME = new QName("", "DOB");
    private final static QName _Gender_QNAME = new QName("", "Gender");
    private final static QName _Coverage_QNAME = new QName("", "Coverage");
    private final static QName _Coverages_QNAME = new QName("", "Coverages");
    private final static QName _HIC_QNAME = new QName("", "HIC");
    private final static QName _Height_QNAME = new QName("", "Height");
    private final static QName _HeightUnits_QNAME = new QName("", "Height_Units");
    private final static QName _Weight_QNAME = new QName("", "Weight");
    private final static QName _WeightUnits_QNAME = new QName("", "Weight_Units");
    private final static QName _WrittenLangPref_QNAME = new QName("", "Written_Lang_Pref");
    private final static QName _SpokenLangPref_QNAME = new QName("", "Spoken_Lang_Pref");
    private final static QName _InterpreterReq_QNAME = new QName("", "Interpreter_Req");
    private final static QName _KPClientIDNumber_QNAME = new QName("", "KP_Client_ID_Number");
    private final static QName _LanguageLineNumber_QNAME = new QName("", "Language_Line_Number");
    private final static QName _ASLNumber_QNAME = new QName("", "ASL_Number");
    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _First_QNAME = new QName("", "First");
    private final static QName _Middle_QNAME = new QName("", "Middle");
    private final static QName _Last_QNAME = new QName("", "Last");
    private final static QName _Suffix_QNAME = new QName("", "Suffix");
    private final static QName _Address_QNAME = new QName("", "Address");
    private final static QName _AddressBusinessName_QNAME = new QName("", "Address_Business_Name");
    private final static QName _AddressLine1_QNAME = new QName("", "Address_Line_1");
    private final static QName _AddressLine2_QNAME = new QName("", "Address_Line_2");
    private final static QName _City_QNAME = new QName("", "City");
    private final static QName _State_QNAME = new QName("", "State");
    private final static QName _Zip_QNAME = new QName("", "Zip");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.apria.gateway.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link OrderEquipmentLine }
     * 
     */
    public OrderEquipmentLine createOrderEquipmentLine() {
        return new OrderEquipmentLine();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link KPOrder }
     * 
     */
    public KPOrder createKPOrder() {
        return new KPOrder();
    }

    /**
     * Create an instance of {@link OrderHeader }
     * 
     */
    public OrderHeader createOrderHeader() {
        return new OrderHeader();
    }

    /**
     * Create an instance of {@link VendorID }
     * 
     */
    public VendorID createVendorID() {
        return new VendorID();
    }

    /**
     * Create an instance of {@link KPOrderID }
     * 
     */
    public KPOrderID createKPOrderID() {
        return new KPOrderID();
    }

    /**
     * Create an instance of {@link VendorOrderID }
     * 
     */
    public VendorOrderID createVendorOrderID() {
        return new VendorOrderID();
    }

    /**
     * Create an instance of {@link OrderLocation }
     * 
     */
    public OrderLocation createOrderLocation() {
        return new OrderLocation();
    }

    /**
     * Create an instance of {@link TransactionType }
     * 
     */
    public TransactionType createTransactionType() {
        return new TransactionType();
    }

    /**
     * Create an instance of {@link OrderID }
     * 
     */
    public OrderID createOrderID() {
        return new OrderID();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link PayorGroup }
     * 
     */
    public PayorGroup createPayorGroup() {
        return new PayorGroup();
    }

    /**
     * Create an instance of {@link MBI }
     * 
     */
    public MBI createMBI() {
        return new MBI();
    }

    /**
     * Create an instance of {@link ICDCD }
     * 
     */
    public ICDCD createICDCD() {
        return new ICDCD();
    }

    /**
     * Create an instance of {@link ICDIND }
     * 
     */
    public ICDIND createICDIND() {
        return new ICDIND();
    }

    /**
     * Create an instance of {@link PlaceOfService }
     * 
     */
    public PlaceOfService createPlaceOfService() {
        return new PlaceOfService();
    }

    /**
     * Create an instance of {@link NotificationSentDate }
     * 
     */
    public NotificationSentDate createNotificationSentDate() {
        return new NotificationSentDate();
    }

    /**
     * Create an instance of {@link NotificationSentTime }
     * 
     */
    public NotificationSentTime createNotificationSentTime() {
        return new NotificationSentTime();
    }

    /**
     * Create an instance of {@link OrderEquipment }
     * 
     */
    public OrderEquipment createOrderEquipment() {
        return new OrderEquipment();
    }

    /**
     * Create an instance of {@link DeliveryAddresses }
     * 
     */
    public DeliveryAddresses createDeliveryAddresses() {
        return new DeliveryAddresses();
    }

    /**
     * Create an instance of {@link OrderNotes }
     * 
     */
    public OrderNotes createOrderNotes() {
        return new OrderNotes();
    }

    /**
     * Create an instance of {@link TransactionDetails }
     * 
     */
    public TransactionDetails createTransactionDetails() {
        return new TransactionDetails();
    }

    /**
     * Create an instance of {@link OrderLine }
     * 
     */
    public OrderLine createOrderLine() {
        return new OrderLine();
    }

    /**
     * Create an instance of {@link LineAddressType }
     * 
     */
    public LineAddressType createLineAddressType() {
        return new LineAddressType();
    }

    /**
     * Create an instance of {@link LineCoverage }
     * 
     */
    public LineCoverage createLineCoverage() {
        return new LineCoverage();
    }

    /**
     * Create an instance of {@link LineItemCode }
     * 
     */
    public LineItemCode createLineItemCode() {
        return new LineItemCode();
    }

    /**
     * Create an instance of {@link LineItemDescription }
     * 
     */
    public LineItemDescription createLineItemDescription() {
        return new LineItemDescription();
    }

    /**
     * Create an instance of {@link LineItemQuantity }
     * 
     */
    public LineItemQuantity createLineItemQuantity() {
        return new LineItemQuantity();
    }

    /**
     * Create an instance of {@link LineServiceStartDate }
     * 
     */
    public LineServiceStartDate createLineServiceStartDate() {
        return new LineServiceStartDate();
    }

    /**
     * Create an instance of {@link LineDurationUnit }
     * 
     */
    public LineDurationUnit createLineDurationUnit() {
        return new LineDurationUnit();
    }

    /**
     * Create an instance of {@link LineDurationOfUse }
     * 
     */
    public LineDurationOfUse createLineDurationOfUse() {
        return new LineDurationOfUse();
    }

    /**
     * Create an instance of {@link LineDeliveryType }
     * 
     */
    public LineDeliveryType createLineDeliveryType() {
        return new LineDeliveryType();
    }

    /**
     * Create an instance of {@link ErrorCodes }
     * 
     */
    public ErrorCodes createErrorCodes() {
        return new ErrorCodes();
    }

    /**
     * Create an instance of {@link LineNotes }
     * 
     */
    public LineNotes createLineNotes() {
        return new LineNotes();
    }

    /**
     * Create an instance of {@link LineNote }
     * 
     */
    public LineNote createLineNote() {
        return new LineNote();
    }

    /**
     * Create an instance of {@link LineNoteID }
     * 
     */
    public LineNoteID createLineNoteID() {
        return new LineNoteID();
    }

    /**
     * Create an instance of {@link LineNoteText }
     * 
     */
    public LineNoteText createLineNoteText() {
        return new LineNoteText();
    }

    /**
     * Create an instance of {@link LineCoPayMethod }
     * 
     */
    public LineCoPayMethod createLineCoPayMethod() {
        return new LineCoPayMethod();
    }

    /**
     * Create an instance of {@link LineCoPayAmount }
     * 
     */
    public LineCoPayAmount createLineCoPayAmount() {
        return new LineCoPayAmount();
    }

    /**
     * Create an instance of {@link LineMemberLiability }
     * 
     */
    public LineMemberLiability createLineMemberLiability() {
        return new LineMemberLiability();
    }

    /**
     * Create an instance of {@link LineKPShare }
     * 
     */
    public LineKPShare createLineKPShare() {
        return new LineKPShare();
    }

    /**
     * Create an instance of {@link LineMedicareShare }
     * 
     */
    public LineMedicareShare createLineMedicareShare() {
        return new LineMedicareShare();
    }

    /**
     * Create an instance of {@link LineRetrievalDate }
     * 
     */
    public LineRetrievalDate createLineRetrievalDate() {
        return new LineRetrievalDate();
    }

    /**
     * Create an instance of {@link LineRetrievalReason }
     * 
     */
    public LineRetrievalReason createLineRetrievalReason() {
        return new LineRetrievalReason();
    }

    /**
     * Create an instance of {@link LineRetrievalType }
     * 
     */
    public LineRetrievalType createLineRetrievalType() {
        return new LineRetrievalType();
    }

    /**
     * Create an instance of {@link DeliveryAddress }
     * 
     */
    public DeliveryAddress createDeliveryAddress() {
        return new DeliveryAddress();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link PrimaryPhone }
     * 
     */
    public PrimaryPhone createPrimaryPhone() {
        return new PrimaryPhone();
    }

    /**
     * Create an instance of {@link SecondaryPhone }
     * 
     */
    public SecondaryPhone createSecondaryPhone() {
        return new SecondaryPhone();
    }

    /**
     * Create an instance of {@link OrderNote }
     * 
     */
    public OrderNote createOrderNote() {
        return new OrderNote();
    }

    /**
     * Create an instance of {@link OrderNoteID }
     * 
     */
    public OrderNoteID createOrderNoteID() {
        return new OrderNoteID();
    }

    /**
     * Create an instance of {@link OrderNoteText }
     * 
     */
    public OrderNoteText createOrderNoteText() {
        return new OrderNoteText();
    }

    /**
     * Create an instance of {@link ContactPerson }
     * 
     */
    public ContactPerson createContactPerson() {
        return new ContactPerson();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link Physician }
     * 
     */
    public Physician createPhysician() {
        return new Physician();
    }

    /**
     * Create an instance of {@link UPIN }
     * 
     */
    public UPIN createUPIN() {
        return new UPIN();
    }

    /**
     * Create an instance of {@link NPIID }
     * 
     */
    public NPIID createNPIID() {
        return new NPIID();
    }

    /**
     * Create an instance of {@link MRN }
     * 
     */
    public MRN createMRN() {
        return new MRN();
    }

    /**
     * Create an instance of {@link DOB }
     * 
     */
    public DOB createDOB() {
        return new DOB();
    }

    /**
     * Create an instance of {@link Gender }
     * 
     */
    public Gender createGender() {
        return new Gender();
    }

    /**
     * Create an instance of {@link Coverage }
     * 
     */
    public Coverage createCoverage() {
        return new Coverage();
    }

    /**
     * Create an instance of {@link Coverages }
     * 
     */
    public Coverages createCoverages() {
        return new Coverages();
    }

    /**
     * Create an instance of {@link HIC }
     * 
     */
    public HIC createHIC() {
        return new HIC();
    }

    /**
     * Create an instance of {@link Height }
     * 
     */
    public Height createHeight() {
        return new Height();
    }

    /**
     * Create an instance of {@link HeightUnits }
     * 
     */
    public HeightUnits createHeightUnits() {
        return new HeightUnits();
    }

    /**
     * Create an instance of {@link Weight }
     * 
     */
    public Weight createWeight() {
        return new Weight();
    }

    /**
     * Create an instance of {@link WeightUnits }
     * 
     */
    public WeightUnits createWeightUnits() {
        return new WeightUnits();
    }

    /**
     * Create an instance of {@link WrittenLangPref }
     * 
     */
    public WrittenLangPref createWrittenLangPref() {
        return new WrittenLangPref();
    }

    /**
     * Create an instance of {@link SpokenLangPref }
     * 
     */
    public SpokenLangPref createSpokenLangPref() {
        return new SpokenLangPref();
    }

    /**
     * Create an instance of {@link InterpreterReq }
     * 
     */
    public InterpreterReq createInterpreterReq() {
        return new InterpreterReq();
    }

    /**
     * Create an instance of {@link KPClientIDNumber }
     * 
     */
    public KPClientIDNumber createKPClientIDNumber() {
        return new KPClientIDNumber();
    }

    /**
     * Create an instance of {@link LanguageLineNumber }
     * 
     */
    public LanguageLineNumber createLanguageLineNumber() {
        return new LanguageLineNumber();
    }

    /**
     * Create an instance of {@link ASLNumber }
     * 
     */
    public ASLNumber createASLNumber() {
        return new ASLNumber();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link First }
     * 
     */
    public First createFirst() {
        return new First();
    }

    /**
     * Create an instance of {@link Middle }
     * 
     */
    public Middle createMiddle() {
        return new Middle();
    }

    /**
     * Create an instance of {@link Last }
     * 
     */
    public Last createLast() {
        return new Last();
    }

    /**
     * Create an instance of {@link Suffix }
     * 
     */
    public Suffix createSuffix() {
        return new Suffix();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AddressBusinessName }
     * 
     */
    public AddressBusinessName createAddressBusinessName() {
        return new AddressBusinessName();
    }

    /**
     * Create an instance of {@link AddressLine1 }
     * 
     */
    public AddressLine1 createAddressLine1() {
        return new AddressLine1();
    }

    /**
     * Create an instance of {@link AddressLine2 }
     * 
     */
    public AddressLine2 createAddressLine2() {
        return new AddressLine2();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link Zip }
     * 
     */
    public Zip createZip() {
        return new Zip();
    }

    /**
     * Create an instance of {@link Patient.CommunicationDevice }
     * 
     */
    public Patient.CommunicationDevice createPatientCommunicationDevice() {
        return new Patient.CommunicationDevice();
    }

    /**
     * Create an instance of {@link OrderEquipmentLine.PricingInformation }
     * 
     */
    public OrderEquipmentLine.PricingInformation createOrderEquipmentLinePricingInformation() {
        return new OrderEquipmentLine.PricingInformation();
    }

    /**
     * Create an instance of {@link Order.Diagnosis }
     * 
     */
    public Order.Diagnosis createOrderDiagnosis() {
        return new Order.Diagnosis();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KPOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "KP_Order")
    public JAXBElement<KPOrder> createKPOrder(KPOrder value) {
        return new JAXBElement<KPOrder>(_KPOrder_QNAME, KPOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Order_Header")
    public JAXBElement<OrderHeader> createOrderHeader(OrderHeader value) {
        return new JAXBElement<OrderHeader>(_OrderHeader_QNAME, OrderHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Order }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Order")
    public JAXBElement<Order> createOrder(Order value) {
        return new JAXBElement<Order>(_Order_QNAME, Order.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VendorID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Vendor_ID")
    public JAXBElement<VendorID> createVendorID(VendorID value) {
        return new JAXBElement<VendorID>(_VendorID_QNAME, VendorID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KPOrderID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "KP_Order_ID")
    public JAXBElement<KPOrderID> createKPOrderID(KPOrderID value) {
        return new JAXBElement<KPOrderID>(_KPOrderID_QNAME, KPOrderID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VendorOrderID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Vendor_Order_ID")
    public JAXBElement<VendorOrderID> createVendorOrderID(VendorOrderID value) {
        return new JAXBElement<VendorOrderID>(_VendorOrderID_QNAME, VendorOrderID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderLocation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Order_Location")
    public JAXBElement<OrderLocation> createOrderLocation(OrderLocation value) {
        return new JAXBElement<OrderLocation>(_OrderLocation_QNAME, OrderLocation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Transaction_Type")
    public JAXBElement<TransactionType> createTransactionType(TransactionType value) {
        return new JAXBElement<TransactionType>(_TransactionType_QNAME, TransactionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Order_ID")
    public JAXBElement<OrderID> createOrderID(OrderID value) {
        return new JAXBElement<OrderID>(_OrderID_QNAME, OrderID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Order_Type")
    public JAXBElement<OrderType> createOrderType(OrderType value) {
        return new JAXBElement<OrderType>(_OrderType_QNAME, OrderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PayorGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Payor_Group")
    public JAXBElement<PayorGroup> createPayorGroup(PayorGroup value) {
        return new JAXBElement<PayorGroup>(_PayorGroup_QNAME, PayorGroup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MBI }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MBI")
    public JAXBElement<MBI> createMBI(MBI value) {
        return new JAXBElement<MBI>(_MBI_QNAME, MBI.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ICDCD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ICD_CD")
    public JAXBElement<ICDCD> createICDCD(ICDCD value) {
        return new JAXBElement<ICDCD>(_ICDCD_QNAME, ICDCD.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ICDIND }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ICD_IND")
    public JAXBElement<ICDIND> createICDIND(ICDIND value) {
        return new JAXBElement<ICDIND>(_ICDIND_QNAME, ICDIND.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaceOfService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Place_Of_Service")
    public JAXBElement<PlaceOfService> createPlaceOfService(PlaceOfService value) {
        return new JAXBElement<PlaceOfService>(_PlaceOfService_QNAME, PlaceOfService.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationSentDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notification_Sent_Date")
    public JAXBElement<NotificationSentDate> createNotificationSentDate(NotificationSentDate value) {
        return new JAXBElement<NotificationSentDate>(_NotificationSentDate_QNAME, NotificationSentDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationSentTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notification_Sent_Time")
    public JAXBElement<NotificationSentTime> createNotificationSentTime(NotificationSentTime value) {
        return new JAXBElement<NotificationSentTime>(_NotificationSentTime_QNAME, NotificationSentTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderEquipment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Order_Equipment")
    public JAXBElement<OrderEquipment> createOrderEquipment(OrderEquipment value) {
        return new JAXBElement<OrderEquipment>(_OrderEquipment_QNAME, OrderEquipment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliveryAddresses }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Delivery_Addresses")
    public JAXBElement<DeliveryAddresses> createDeliveryAddresses(DeliveryAddresses value) {
        return new JAXBElement<DeliveryAddresses>(_DeliveryAddresses_QNAME, DeliveryAddresses.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderNotes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Order_Notes")
    public JAXBElement<OrderNotes> createOrderNotes(OrderNotes value) {
        return new JAXBElement<OrderNotes>(_OrderNotes_QNAME, OrderNotes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Transaction_Details")
    public JAXBElement<TransactionDetails> createTransactionDetails(TransactionDetails value) {
        return new JAXBElement<TransactionDetails>(_TransactionDetails_QNAME, TransactionDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderEquipmentLine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Order_Equipment_Line")
    public JAXBElement<OrderEquipmentLine> createOrderEquipmentLine(OrderEquipmentLine value) {
        return new JAXBElement<OrderEquipmentLine>(_OrderEquipmentLine_QNAME, OrderEquipmentLine.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderLine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Order_Line")
    public JAXBElement<OrderLine> createOrderLine(OrderLine value) {
        return new JAXBElement<OrderLine>(_OrderLine_QNAME, OrderLine.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Address_Type")
    public JAXBElement<LineAddressType> createLineAddressType(LineAddressType value) {
        return new JAXBElement<LineAddressType>(_LineAddressType_QNAME, LineAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineCoverage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Coverage")
    public JAXBElement<LineCoverage> createLineCoverage(LineCoverage value) {
        return new JAXBElement<LineCoverage>(_LineCoverage_QNAME, LineCoverage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineItemCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Item_Code")
    public JAXBElement<LineItemCode> createLineItemCode(LineItemCode value) {
        return new JAXBElement<LineItemCode>(_LineItemCode_QNAME, LineItemCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineItemDescription }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Item_Description")
    public JAXBElement<LineItemDescription> createLineItemDescription(LineItemDescription value) {
        return new JAXBElement<LineItemDescription>(_LineItemDescription_QNAME, LineItemDescription.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineItemQuantity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Item_Quantity")
    public JAXBElement<LineItemQuantity> createLineItemQuantity(LineItemQuantity value) {
        return new JAXBElement<LineItemQuantity>(_LineItemQuantity_QNAME, LineItemQuantity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineServiceStartDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Service_Start_Date")
    public JAXBElement<LineServiceStartDate> createLineServiceStartDate(LineServiceStartDate value) {
        return new JAXBElement<LineServiceStartDate>(_LineServiceStartDate_QNAME, LineServiceStartDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineDurationUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Duration_Unit")
    public JAXBElement<LineDurationUnit> createLineDurationUnit(LineDurationUnit value) {
        return new JAXBElement<LineDurationUnit>(_LineDurationUnit_QNAME, LineDurationUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineDurationOfUse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Duration_Of_Use")
    public JAXBElement<LineDurationOfUse> createLineDurationOfUse(LineDurationOfUse value) {
        return new JAXBElement<LineDurationOfUse>(_LineDurationOfUse_QNAME, LineDurationOfUse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineDeliveryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Delivery_Type")
    public JAXBElement<LineDeliveryType> createLineDeliveryType(LineDeliveryType value) {
        return new JAXBElement<LineDeliveryType>(_LineDeliveryType_QNAME, LineDeliveryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorCodes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Error_Codes")
    public JAXBElement<ErrorCodes> createErrorCodes(ErrorCodes value) {
        return new JAXBElement<ErrorCodes>(_ErrorCodes_QNAME, ErrorCodes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineNotes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Notes")
    public JAXBElement<LineNotes> createLineNotes(LineNotes value) {
        return new JAXBElement<LineNotes>(_LineNotes_QNAME, LineNotes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineNote }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Note")
    public JAXBElement<LineNote> createLineNote(LineNote value) {
        return new JAXBElement<LineNote>(_LineNote_QNAME, LineNote.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineNoteID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Note_ID")
    public JAXBElement<LineNoteID> createLineNoteID(LineNoteID value) {
        return new JAXBElement<LineNoteID>(_LineNoteID_QNAME, LineNoteID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineNoteText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Note_Text")
    public JAXBElement<LineNoteText> createLineNoteText(LineNoteText value) {
        return new JAXBElement<LineNoteText>(_LineNoteText_QNAME, LineNoteText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineCoPayMethod }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_CoPay_Method")
    public JAXBElement<LineCoPayMethod> createLineCoPayMethod(LineCoPayMethod value) {
        return new JAXBElement<LineCoPayMethod>(_LineCoPayMethod_QNAME, LineCoPayMethod.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineCoPayAmount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_CoPay_Amount")
    public JAXBElement<LineCoPayAmount> createLineCoPayAmount(LineCoPayAmount value) {
        return new JAXBElement<LineCoPayAmount>(_LineCoPayAmount_QNAME, LineCoPayAmount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineMemberLiability }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Member_Liability")
    public JAXBElement<LineMemberLiability> createLineMemberLiability(LineMemberLiability value) {
        return new JAXBElement<LineMemberLiability>(_LineMemberLiability_QNAME, LineMemberLiability.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineKPShare }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_KP_Share")
    public JAXBElement<LineKPShare> createLineKPShare(LineKPShare value) {
        return new JAXBElement<LineKPShare>(_LineKPShare_QNAME, LineKPShare.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineMedicareShare }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Medicare_Share")
    public JAXBElement<LineMedicareShare> createLineMedicareShare(LineMedicareShare value) {
        return new JAXBElement<LineMedicareShare>(_LineMedicareShare_QNAME, LineMedicareShare.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineRetrievalDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Retrieval_Date")
    public JAXBElement<LineRetrievalDate> createLineRetrievalDate(LineRetrievalDate value) {
        return new JAXBElement<LineRetrievalDate>(_LineRetrievalDate_QNAME, LineRetrievalDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineRetrievalReason }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Retrieval_Reason")
    public JAXBElement<LineRetrievalReason> createLineRetrievalReason(LineRetrievalReason value) {
        return new JAXBElement<LineRetrievalReason>(_LineRetrievalReason_QNAME, LineRetrievalReason.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineRetrievalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Line_Retrieval_Type")
    public JAXBElement<LineRetrievalType> createLineRetrievalType(LineRetrievalType value) {
        return new JAXBElement<LineRetrievalType>(_LineRetrievalType_QNAME, LineRetrievalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliveryAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Delivery_Address")
    public JAXBElement<DeliveryAddress> createDeliveryAddress(DeliveryAddress value) {
        return new JAXBElement<DeliveryAddress>(_DeliveryAddress_QNAME, DeliveryAddress.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address_Type")
    public JAXBElement<AddressType> createAddressType(AddressType value) {
        return new JAXBElement<AddressType>(_AddressType_QNAME, AddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimaryPhone }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Primary_Phone")
    public JAXBElement<PrimaryPhone> createPrimaryPhone(PrimaryPhone value) {
        return new JAXBElement<PrimaryPhone>(_PrimaryPhone_QNAME, PrimaryPhone.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecondaryPhone }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Secondary_Phone")
    public JAXBElement<SecondaryPhone> createSecondaryPhone(SecondaryPhone value) {
        return new JAXBElement<SecondaryPhone>(_SecondaryPhone_QNAME, SecondaryPhone.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderNote }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Order_Note")
    public JAXBElement<OrderNote> createOrderNote(OrderNote value) {
        return new JAXBElement<OrderNote>(_OrderNote_QNAME, OrderNote.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderNoteID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Order_Note_ID")
    public JAXBElement<OrderNoteID> createOrderNoteID(OrderNoteID value) {
        return new JAXBElement<OrderNoteID>(_OrderNoteID_QNAME, OrderNoteID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderNoteText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Order_Note_Text")
    public JAXBElement<OrderNoteText> createOrderNoteText(OrderNoteText value) {
        return new JAXBElement<OrderNoteText>(_OrderNoteText_QNAME, OrderNoteText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactPerson }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Contact_Person")
    public JAXBElement<ContactPerson> createContactPerson(ContactPerson value) {
        return new JAXBElement<ContactPerson>(_ContactPerson_QNAME, ContactPerson.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Phone }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Phone")
    public JAXBElement<Phone> createPhone(Phone value) {
        return new JAXBElement<Phone>(_Phone_QNAME, Phone.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Physician }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Physician")
    public JAXBElement<Physician> createPhysician(Physician value) {
        return new JAXBElement<Physician>(_Physician_QNAME, Physician.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UPIN }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UPIN")
    public JAXBElement<UPIN> createUPIN(UPIN value) {
        return new JAXBElement<UPIN>(_UPIN_QNAME, UPIN.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NPIID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NPI_ID")
    public JAXBElement<NPIID> createNPIID(NPIID value) {
        return new JAXBElement<NPIID>(_NPIID_QNAME, NPIID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Patient }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Patient")
    public JAXBElement<Patient> createPatient(Patient value) {
        return new JAXBElement<Patient>(_Patient_QNAME, Patient.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MRN }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MRN")
    public JAXBElement<MRN> createMRN(MRN value) {
        return new JAXBElement<MRN>(_MRN_QNAME, MRN.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DOB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOB")
    public JAXBElement<DOB> createDOB(DOB value) {
        return new JAXBElement<DOB>(_DOB_QNAME, DOB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Gender }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Gender")
    public JAXBElement<Gender> createGender(Gender value) {
        return new JAXBElement<Gender>(_Gender_QNAME, Gender.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Coverage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Coverage")
    public JAXBElement<Coverage> createCoverage(Coverage value) {
        return new JAXBElement<Coverage>(_Coverage_QNAME, Coverage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Coverages }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Coverages")
    public JAXBElement<Coverages> createCoverages(Coverages value) {
        return new JAXBElement<Coverages>(_Coverages_QNAME, Coverages.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HIC }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HIC")
    public JAXBElement<HIC> createHIC(HIC value) {
        return new JAXBElement<HIC>(_HIC_QNAME, HIC.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Height }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Height")
    public JAXBElement<Height> createHeight(Height value) {
        return new JAXBElement<Height>(_Height_QNAME, Height.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HeightUnits }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Height_Units")
    public JAXBElement<HeightUnits> createHeightUnits(HeightUnits value) {
        return new JAXBElement<HeightUnits>(_HeightUnits_QNAME, HeightUnits.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Weight }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Weight")
    public JAXBElement<Weight> createWeight(Weight value) {
        return new JAXBElement<Weight>(_Weight_QNAME, Weight.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WeightUnits }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Weight_Units")
    public JAXBElement<WeightUnits> createWeightUnits(WeightUnits value) {
        return new JAXBElement<WeightUnits>(_WeightUnits_QNAME, WeightUnits.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WrittenLangPref }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Written_Lang_Pref")
    public JAXBElement<WrittenLangPref> createWrittenLangPref(WrittenLangPref value) {
        return new JAXBElement<WrittenLangPref>(_WrittenLangPref_QNAME, WrittenLangPref.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpokenLangPref }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Spoken_Lang_Pref")
    public JAXBElement<SpokenLangPref> createSpokenLangPref(SpokenLangPref value) {
        return new JAXBElement<SpokenLangPref>(_SpokenLangPref_QNAME, SpokenLangPref.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InterpreterReq }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Interpreter_Req")
    public JAXBElement<InterpreterReq> createInterpreterReq(InterpreterReq value) {
        return new JAXBElement<InterpreterReq>(_InterpreterReq_QNAME, InterpreterReq.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KPClientIDNumber }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "KP_Client_ID_Number")
    public JAXBElement<KPClientIDNumber> createKPClientIDNumber(KPClientIDNumber value) {
        return new JAXBElement<KPClientIDNumber>(_KPClientIDNumber_QNAME, KPClientIDNumber.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageLineNumber }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Language_Line_Number")
    public JAXBElement<LanguageLineNumber> createLanguageLineNumber(LanguageLineNumber value) {
        return new JAXBElement<LanguageLineNumber>(_LanguageLineNumber_QNAME, LanguageLineNumber.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ASLNumber }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ASL_Number")
    public JAXBElement<ASLNumber> createASLNumber(ASLNumber value) {
        return new JAXBElement<ASLNumber>(_ASLNumber_QNAME, ASLNumber.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Name }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<Name> createName(Name value) {
        return new JAXBElement<Name>(_Name_QNAME, Name.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link First }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "First")
    public JAXBElement<First> createFirst(First value) {
        return new JAXBElement<First>(_First_QNAME, First.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Middle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Middle")
    public JAXBElement<Middle> createMiddle(Middle value) {
        return new JAXBElement<Middle>(_Middle_QNAME, Middle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Last }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Last")
    public JAXBElement<Last> createLast(Last value) {
        return new JAXBElement<Last>(_Last_QNAME, Last.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Suffix }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Suffix")
    public JAXBElement<Suffix> createSuffix(Suffix value) {
        return new JAXBElement<Suffix>(_Suffix_QNAME, Suffix.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address")
    public JAXBElement<Address> createAddress(Address value) {
        return new JAXBElement<Address>(_Address_QNAME, Address.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressBusinessName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address_Business_Name")
    public JAXBElement<AddressBusinessName> createAddressBusinessName(AddressBusinessName value) {
        return new JAXBElement<AddressBusinessName>(_AddressBusinessName_QNAME, AddressBusinessName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressLine1 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address_Line_1")
    public JAXBElement<AddressLine1> createAddressLine1(AddressLine1 value) {
        return new JAXBElement<AddressLine1>(_AddressLine1_QNAME, AddressLine1 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressLine2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address_Line_2")
    public JAXBElement<AddressLine2> createAddressLine2(AddressLine2 value) {
        return new JAXBElement<AddressLine2>(_AddressLine2_QNAME, AddressLine2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link City }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "City")
    public JAXBElement<City> createCity(City value) {
        return new JAXBElement<City>(_City_QNAME, City.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link State }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "State")
    public JAXBElement<State> createState(State value) {
        return new JAXBElement<State>(_State_QNAME, State.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Zip }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Zip")
    public JAXBElement<Zip> createZip(Zip value) {
        return new JAXBElement<Zip>(_Zip_QNAME, Zip.class, null, value);
    }

}
