//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.24 at 11:55:59 AM EDT 
//


package com.apria.gateway.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Order_Note complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Order_Note"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Order_Note_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}Order_Note_Text" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Order_Note", propOrder = {
    "orderNoteID",
    "orderNoteText"
})
public class OrderNote {

    @XmlElement(name = "Order_Note_ID")
    protected OrderNoteID orderNoteID;
    @XmlElement(name = "Order_Note_Text")
    protected OrderNoteText orderNoteText;

    /**
     * Gets the value of the orderNoteID property.
     * 
     * @return
     *     possible object is
     *     {@link OrderNoteID }
     *     
     */
    public OrderNoteID getOrderNoteID() {
        return orderNoteID;
    }

    /**
     * Sets the value of the orderNoteID property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderNoteID }
     *     
     */
    public void setOrderNoteID(OrderNoteID value) {
        this.orderNoteID = value;
    }

    /**
     * Gets the value of the orderNoteText property.
     * 
     * @return
     *     possible object is
     *     {@link OrderNoteText }
     *     
     */
    public OrderNoteText getOrderNoteText() {
        return orderNoteText;
    }

    /**
     * Sets the value of the orderNoteText property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderNoteText }
     *     
     */
    public void setOrderNoteText(OrderNoteText value) {
        this.orderNoteText = value;
    }

}
