//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.24 at 11:55:59 AM EDT 
//


package com.apria.gateway.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Patient complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Patient"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}MRN"/&gt;
 *         &lt;element ref="{}Name"/&gt;
 *         &lt;element ref="{}Address" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Communication_Device" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Device_Line" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *                   &lt;element name="Device_Number" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *                   &lt;element name="Extension_Number" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *                   &lt;element name="Device_Location" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *                   &lt;element name="Device_Type" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref="{}DOB"/&gt;
 *         &lt;element ref="{}Gender"/&gt;
 *         &lt;element ref="{}Coverages" minOccurs="0"/&gt;
 *         &lt;element ref="{}Height" minOccurs="0"/&gt;
 *         &lt;element ref="{}Weight" minOccurs="0"/&gt;
 *         &lt;element name="SPO2" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element ref="{}Written_Lang_Pref" minOccurs="0"/&gt;
 *         &lt;element ref="{}Spoken_Lang_Pref" minOccurs="0"/&gt;
 *         &lt;element ref="{}Interpreter_Req" minOccurs="0"/&gt;
 *         &lt;element ref="{}KP_Client_ID_Number" minOccurs="0"/&gt;
 *         &lt;element ref="{}Language_Line_Number" minOccurs="0"/&gt;
 *         &lt;element ref="{}ASL_Number" minOccurs="0"/&gt;
 *         &lt;element name="Generic_1" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element name="Generic_2" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element name="Generic_3" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Patient", propOrder = {
    "mrn",
    "name",
    "address",
    "communicationDevice",
    "dob",
    "gender",
    "coverages",
    "height",
    "weight",
    "spo2",
    "writtenLangPref",
    "spokenLangPref",
    "interpreterReq",
    "kpClientIDNumber",
    "languageLineNumber",
    "aslNumber",
    "generic1",
    "generic2",
    "generic3"
})
public class Patient {

    @XmlElement(name = "MRN", required = true)
    protected MRN mrn;
    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "Address")
    protected List<Address> address;
    @XmlElement(name = "Communication_Device")
    protected List<Patient.CommunicationDevice> communicationDevice;
    @XmlElement(name = "DOB", required = true)
    protected DOB dob;
    @XmlElement(name = "Gender", required = true)
    protected Gender gender;
    @XmlElement(name = "Coverages")
    protected Coverages coverages;
    @XmlElement(name = "Height")
    protected Height height;
    @XmlElement(name = "Weight")
    protected Weight weight;
    @XmlElement(name = "SPO2")
    protected Object spo2;
    @XmlElement(name = "Written_Lang_Pref")
    protected WrittenLangPref writtenLangPref;
    @XmlElement(name = "Spoken_Lang_Pref")
    protected SpokenLangPref spokenLangPref;
    @XmlElement(name = "Interpreter_Req")
    protected InterpreterReq interpreterReq;
    @XmlElement(name = "KP_Client_ID_Number")
    protected KPClientIDNumber kpClientIDNumber;
    @XmlElement(name = "Language_Line_Number")
    protected LanguageLineNumber languageLineNumber;
    @XmlElement(name = "ASL_Number")
    protected ASLNumber aslNumber;
    @XmlElement(name = "Generic_1")
    protected Object generic1;
    @XmlElement(name = "Generic_2")
    protected Object generic2;
    @XmlElement(name = "Generic_3")
    protected Object generic3;

    /**
     * Gets the value of the mrn property.
     * 
     * @return
     *     possible object is
     *     {@link MRN }
     *     
     */
    public MRN getMRN() {
        return mrn;
    }

    /**
     * Sets the value of the mrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link MRN }
     *     
     */
    public void setMRN(MRN value) {
        this.mrn = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     * 
     * 
     */
    public List<Address> getAddress() {
        if (address == null) {
            address = new ArrayList<Address>();
        }
        return this.address;
    }

    /**
     * Gets the value of the communicationDevice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the communicationDevice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommunicationDevice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Patient.CommunicationDevice }
     * 
     * 
     */
    public List<Patient.CommunicationDevice> getCommunicationDevice() {
        if (communicationDevice == null) {
            communicationDevice = new ArrayList<Patient.CommunicationDevice>();
        }
        return this.communicationDevice;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link DOB }
     *     
     */
    public DOB getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOB }
     *     
     */
    public void setDOB(DOB value) {
        this.dob = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link Gender }
     *     
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gender }
     *     
     */
    public void setGender(Gender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the coverages property.
     * 
     * @return
     *     possible object is
     *     {@link Coverages }
     *     
     */
    public Coverages getCoverages() {
        return coverages;
    }

    /**
     * Sets the value of the coverages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coverages }
     *     
     */
    public void setCoverages(Coverages value) {
        this.coverages = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Height }
     *     
     */
    public Height getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Height }
     *     
     */
    public void setHeight(Height value) {
        this.height = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Weight }
     *     
     */
    public Weight getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weight }
     *     
     */
    public void setWeight(Weight value) {
        this.weight = value;
    }

    /**
     * Gets the value of the spo2 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSPO2() {
        return spo2;
    }

    /**
     * Sets the value of the spo2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSPO2(Object value) {
        this.spo2 = value;
    }

    /**
     * Gets the value of the writtenLangPref property.
     * 
     * @return
     *     possible object is
     *     {@link WrittenLangPref }
     *     
     */
    public WrittenLangPref getWrittenLangPref() {
        return writtenLangPref;
    }

    /**
     * Sets the value of the writtenLangPref property.
     * 
     * @param value
     *     allowed object is
     *     {@link WrittenLangPref }
     *     
     */
    public void setWrittenLangPref(WrittenLangPref value) {
        this.writtenLangPref = value;
    }

    /**
     * Gets the value of the spokenLangPref property.
     * 
     * @return
     *     possible object is
     *     {@link SpokenLangPref }
     *     
     */
    public SpokenLangPref getSpokenLangPref() {
        return spokenLangPref;
    }

    /**
     * Sets the value of the spokenLangPref property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpokenLangPref }
     *     
     */
    public void setSpokenLangPref(SpokenLangPref value) {
        this.spokenLangPref = value;
    }

    /**
     * Gets the value of the interpreterReq property.
     * 
     * @return
     *     possible object is
     *     {@link InterpreterReq }
     *     
     */
    public InterpreterReq getInterpreterReq() {
        return interpreterReq;
    }

    /**
     * Sets the value of the interpreterReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterpreterReq }
     *     
     */
    public void setInterpreterReq(InterpreterReq value) {
        this.interpreterReq = value;
    }

    /**
     * Gets the value of the kpClientIDNumber property.
     * 
     * @return
     *     possible object is
     *     {@link KPClientIDNumber }
     *     
     */
    public KPClientIDNumber getKPClientIDNumber() {
        return kpClientIDNumber;
    }

    /**
     * Sets the value of the kpClientIDNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link KPClientIDNumber }
     *     
     */
    public void setKPClientIDNumber(KPClientIDNumber value) {
        this.kpClientIDNumber = value;
    }

    /**
     * Gets the value of the languageLineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageLineNumber }
     *     
     */
    public LanguageLineNumber getLanguageLineNumber() {
        return languageLineNumber;
    }

    /**
     * Sets the value of the languageLineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageLineNumber }
     *     
     */
    public void setLanguageLineNumber(LanguageLineNumber value) {
        this.languageLineNumber = value;
    }

    /**
     * Gets the value of the aslNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ASLNumber }
     *     
     */
    public ASLNumber getASLNumber() {
        return aslNumber;
    }

    /**
     * Sets the value of the aslNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ASLNumber }
     *     
     */
    public void setASLNumber(ASLNumber value) {
        this.aslNumber = value;
    }

    /**
     * Gets the value of the generic1 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGeneric1() {
        return generic1;
    }

    /**
     * Sets the value of the generic1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGeneric1(Object value) {
        this.generic1 = value;
    }

    /**
     * Gets the value of the generic2 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGeneric2() {
        return generic2;
    }

    /**
     * Sets the value of the generic2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGeneric2(Object value) {
        this.generic2 = value;
    }

    /**
     * Gets the value of the generic3 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGeneric3() {
        return generic3;
    }

    /**
     * Sets the value of the generic3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGeneric3(Object value) {
        this.generic3 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Device_Line" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
     *         &lt;element name="Device_Number" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
     *         &lt;element name="Extension_Number" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
     *         &lt;element name="Device_Location" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
     *         &lt;element name="Device_Type" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deviceLine",
        "deviceNumber",
        "extensionNumber",
        "deviceLocation",
        "deviceType"
    })
    public static class CommunicationDevice {

        @XmlElement(name = "Device_Line")
        protected Object deviceLine;
        @XmlElement(name = "Device_Number")
        protected Object deviceNumber;
        @XmlElement(name = "Extension_Number")
        protected Object extensionNumber;
        @XmlElement(name = "Device_Location")
        protected Object deviceLocation;
        @XmlElement(name = "Device_Type")
        protected Object deviceType;

        /**
         * Gets the value of the deviceLine property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDeviceLine() {
            return deviceLine;
        }

        /**
         * Sets the value of the deviceLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDeviceLine(Object value) {
            this.deviceLine = value;
        }

        /**
         * Gets the value of the deviceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDeviceNumber() {
            return deviceNumber;
        }

        /**
         * Sets the value of the deviceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDeviceNumber(Object value) {
            this.deviceNumber = value;
        }

        /**
         * Gets the value of the extensionNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getExtensionNumber() {
            return extensionNumber;
        }

        /**
         * Sets the value of the extensionNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setExtensionNumber(Object value) {
            this.extensionNumber = value;
        }

        /**
         * Gets the value of the deviceLocation property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDeviceLocation() {
            return deviceLocation;
        }

        /**
         * Sets the value of the deviceLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDeviceLocation(Object value) {
            this.deviceLocation = value;
        }

        /**
         * Gets the value of the deviceType property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDeviceType() {
            return deviceType;
        }

        /**
         * Sets the value of the deviceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDeviceType(Object value) {
            this.deviceType = value;
        }

    }

}
