//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.24 at 11:55:59 AM EDT 
//


package com.apria.gateway.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Physician complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Physician"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Name" minOccurs="0"/&gt;
 *         &lt;element ref="{}UPIN" minOccurs="0"/&gt;
 *         &lt;element ref="{}NPI_ID" minOccurs="0"/&gt;
 *         &lt;element name="Generic_1" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element name="Generic_2" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element name="Generic_3" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Physician", propOrder = {
    "name",
    "upin",
    "npiid",
    "generic1",
    "generic2",
    "generic3"
})
public class Physician {

    @XmlElement(name = "Name")
    protected Name name;
    @XmlElement(name = "UPIN")
    protected UPIN upin;
    @XmlElement(name = "NPI_ID")
    protected NPIID npiid;
    @XmlElement(name = "Generic_1")
    protected Object generic1;
    @XmlElement(name = "Generic_2")
    protected Object generic2;
    @XmlElement(name = "Generic_3")
    protected Object generic3;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the upin property.
     * 
     * @return
     *     possible object is
     *     {@link UPIN }
     *     
     */
    public UPIN getUPIN() {
        return upin;
    }

    /**
     * Sets the value of the upin property.
     * 
     * @param value
     *     allowed object is
     *     {@link UPIN }
     *     
     */
    public void setUPIN(UPIN value) {
        this.upin = value;
    }

    /**
     * Gets the value of the npiid property.
     * 
     * @return
     *     possible object is
     *     {@link NPIID }
     *     
     */
    public NPIID getNPIID() {
        return npiid;
    }

    /**
     * Sets the value of the npiid property.
     * 
     * @param value
     *     allowed object is
     *     {@link NPIID }
     *     
     */
    public void setNPIID(NPIID value) {
        this.npiid = value;
    }

    /**
     * Gets the value of the generic1 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGeneric1() {
        return generic1;
    }

    /**
     * Sets the value of the generic1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGeneric1(Object value) {
        this.generic1 = value;
    }

    /**
     * Gets the value of the generic2 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGeneric2() {
        return generic2;
    }

    /**
     * Sets the value of the generic2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGeneric2(Object value) {
        this.generic2 = value;
    }

    /**
     * Gets the value of the generic3 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGeneric3() {
        return generic3;
    }

    /**
     * Sets the value of the generic3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGeneric3(Object value) {
        this.generic3 = value;
    }

}
