apiVersion: v1
data:
  configuration.properties: |-
    edi.activemq.broker-url=amqp://external-amq7-service:61616
    edi.activemq.user=admin
    emailNotification.noReply.fromEmail=veejay.konda@gmail.com
    emailNotification.error.toEmail=vbkonda@gmail.com
    emailNotification.password=password
    smtp.host=smtp.gmail.com
    smtp.port=465
kind: ConfigMap
metadata:
  name: validationservice-configmap
  namespace: edi-validationservice