//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 02:15:52 PM EST 
//


package com.apria.gateway.err.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.apria.gateway.err.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IncomingEDIMessageError_QNAME = new QName("http://edigateway.apria.com/error", "IncomingEDIMessageError");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.apria.gateway.err.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IncomingEDIMessageErrorType }
     * 
     */
    public IncomingEDIMessageErrorType createIncomingEDIMessageErrorType() {
        return new IncomingEDIMessageErrorType();
    }

    /**
     * Create an instance of {@link ErrorDetailType }
     * 
     */
    public ErrorDetailType createErrorDetailType() {
        return new ErrorDetailType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IncomingEDIMessageErrorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://edigateway.apria.com/error", name = "IncomingEDIMessageError")
    public JAXBElement<IncomingEDIMessageErrorType> createIncomingEDIMessageError(IncomingEDIMessageErrorType value) {
        return new JAXBElement<IncomingEDIMessageErrorType>(_IncomingEDIMessageError_QNAME, IncomingEDIMessageErrorType.class, null, value);
    }

}
